export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_QUANTITY = 'REMOVE_QUANTITY';
export const SET_QUANTITY = 'SET_QUANTITY';
export const FETCH_QUANTITY_FAILED = 'FETCH_QUANTITY_FAILED';

export const PURCHASE_TIRE_SUCCESS = 'PURCHASE_TIRE_SUCCESS';
export const PURCHASE_TIRE_FAIL = 'PURCHASE_TIRE_FAIL';
export const PURCHASE_TIRE_START = 'PURCHASE_TIRE_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';