export const ADD_QUANTITY = 'ADD_QUANTITY';
export const REMOVE_QUANTITY = 'REMOVE_QUANTITY';
export const SET_QUANTITY = 'SET_QUANTITY';
export const FETCH_QUANTITY_FAILED = 'FETCH_QUANTITY_FAILED';

export const PURCHASE_TIRE_SUCCESS = 'PURCHASE_TIRE_SUCCESS';
export const PURCHASE_TIRE_FAIL = 'PURCHASE_TIRE_FAIL';